FROM ubuntu:latest

RUN apt update && apt install -y python3 python3-pip

RUN python3 -m pip install requests flask joblib pandas sklearn pymysql

COPY backend/app.py .
COPY models/Model_D50_N25/model_cols models/Model_D50_N25/whole_dataset.joblib ./

ENTRYPOINT [ "python3" ]

CMD [ "app.py" ]
